In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print( arr.shape)
print( arr.size)
print(arr.dtype)

(5,)
5
int64


In [ ]:
import numpy as np
arr = np.arange(1, 13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
a=np.zeros((25,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
a=np.ones(())
print(a)

1.0


In [ ]:
import numpy as np
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
e=np.arange(10,51,2)
print(e)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
a=np.linspace(0,1,10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([60, 70, 80, 90])
print(a+b)

[ 70  90 110 130]


In [ ]:
a=np.array([1,2,3])
print(a**2)

[1 4 9]


In [ ]:
a=np.array([100,200,300,400])
print(a*1.15)

[115. 230. 345. 460.]


In [ ]:
a=np.array([1,2,3,51,5])
b=np.array([10,20,30,40,50])
print(np.maximum(a,b))
print(np.minimum(a,b))

[10 20 30 51 50]
[ 1  2  3 40  5]


In [ ]:
a=np.arange(0,21)
print(a[0:5])
print(a[15:20])
print(a[5:16])
print(a[::2])

[0 1 2 3 4]
[15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
a= np.array([10, 20, 30, 40, 50, 60, 70, 80])
a[:5] = 100
print(a)

[100 100 100 100 100  60  70  80]


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
reverse = arr[::-1]
print(reverse)

[50 40 30 20 10]


In [ ]:
mat = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
a= mat[1]
b= mat[:, 2]
c= mat[1, 1]
print(a)
print(b)
print(c)

[40 50 60]
[30 60 90]
50


In [ ]:
a= matrix[0:2, 1:3]
print(a)

[[20 30]
 [50 60]]


In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
print("Matrix:")
print(matrix)
print(matrix[0])
print( matrix[:, -1])
print(matrix[2, 2])
print(matrix[0:3, 0:3])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
13
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

print(matrix.transpose())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
arr = np.arange(1, 25).reshape(2, 3, 4)
print(arr)
print(arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
addition = A + B
multiplication = A * B
print(addition)
print(multiplication)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
AT = A.T
result = np.dot(AT, A)
print(A)
print(AT)
print(result)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [ ]:
arr = np.array([1, 4, 9, 16, 25])
result = np.sqrt(arr)
print(result)

[1. 2. 3. 4. 5.]


In [ ]:
arr = np.array([0, 1, 2, 3])
result = np.exp(arr)
print(result)

[ 1.          2.71828183  7.3890561  20.08553692]


In [ ]:
arr = np.random.randn(5)
print(arr)
print(np.sqrt(np.abs(arr)))
print(np.exp(arr))
print(np.abs(arr))

[ 0.41124825 -1.63080123  0.02207206  0.79616489  1.06517455]
[0.6412864  1.27702828 0.1485667  0.89228072 1.03207294]
[1.50869984 0.19577265 1.02231745 2.21702208 2.90134536]
[0.41124825 1.63080123 0.02207206 0.79616489 1.06517455]


In [ ]:
A = np.random.randint(1, 20, 5)
B = np.random.randint(1, 20, 5)
result = np.maximum(A, B)
print("A:", A)
print("B:", B)
print("Element-wise maximum:", result)

A: [ 9 14 12  4 18]
B: [12 19  3 16 14]
Element-wise maximum: [12 19 12 16 18]


In [ ]:
marks = np.array([35, 72, 48, 90, 55, 28])
result = np.where(marks < 40, 0, marks)
print(result)

[ 0 72 48 90 55  0]


In [ ]:
import numpy as np
income = np.array([25000, 55000, 48000, 75000, 30000])
result = np.where(income >= 50000, "High", "Low")
print(result)

['Low' 'High' 'Low' 'High' 'Low']


In [ ]:
arr = np.array([10, 25, 35, 40, 15, 50])
result = np.where(arr > 30, 100, arr)
print(result)

[ 10  25 100 100  15 100]


In [ ]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(np.sum(matrix))
print(np.mean(matrix))
print(np.var(matrix))
print(np.std(matrix))

450
50.0
666.6666666666666
25.81988897471611


In [ ]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(np.sum(matrix, axis=1))
print(np.sum(matrix, axis=0))

[ 60 150 240]
[120 150 180]


In [ ]:
marks = np.array([65, 78, 45, 89, 92, 56, 72, 81, 60, 75])
print(np.mean(marks))
print(np.std(marks))
print(np.min(marks))
print( np.max(marks))

71.3
14.1
45
92


In [ ]:
arr1 = np.array([True, True, True])
print("any:", np.any(arr1))
print("all:", np.all(arr1))

any: True
all: True


In [ ]:
arr = np.random.randint(1, 100, 10)
print( arr)
print(np.sort(arr))

[61 74  3 96 28 98 63 66  6 82]
[ 3  6 28 61 63 66 74 82 96 98]


In [ ]:
arr = np.array([10, 20, 10, 30, 20, 40, 30, 10])
unique_values = np.unique(arr)
print(unique_values)

[10 20 30 40]


In [ ]:
marks = np.array([85, 90, 75, 85, 60, 90, 75, 95, 60])
unique_marks = np.unique(marks)
print("Unique marks:", unique_marks)

Unique marks: [60 75 85 90 95]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
selected = np.array([20, 40, 60])
result = np.in1d(selected, arr)
print(result)

[ True  True False]


/tmp/ipykernel_1400/1779436539.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  result = np.in1d(selected, arr)


In [50]:
import numpy as np
marks = np.array([
    [65, 70, 80],
    [45, 50, 55],
    [80, 75, 90],
    [35, 40, 45],
    [60, 55, 70],
    [90, 85, 95],
    [40, 45, 50],
    [72, 68, 75],
    [55, 60, 65],
    [30, 35, 40]
])
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
print("Marks:")
print(marks)
print("\nTotal marks:")
print(total)
print("\nAverage marks:")
print(average)
students = np.where(average >= 50)[0]
print("\nStudents with average >= 50:")
print(students)

Marks:
[[65 70 80]
 [45 50 55]
 [80 75 90]
 [35 40 45]
 [60 55 70]
 [90 85 95]
 [40 45 50]
 [72 68 75]
 [55 60 65]
 [30 35 40]]

Total marks:
[215 150 245 120 185 270 135 215 180 105]

Average marks:
[71.66666667 50.         81.66666667 40.         61.66666667 90.
 45.         71.66666667 60.         35.        ]

Students with average >= 50:
[0 1 2 4 5 7 8]


In [51]:
import numpy as np
matrix = np.arange(1, 17).reshape(4, 4)
print("Matrix:")
print(matrix)
transpose = matrix.T
print("\nTranspose:")
print(transpose)
row_sum = np.sum(matrix, axis=1)
print("\nRow-wise sums:")
print(row_sum)
column_sum = np.sum(matrix, axis=0)
print("\nColumn-wise sums:")
print(column_sum)
print("\nMean:", np.mean(matrix))
print("Maximum:", np.max(matrix))
print("Minimum:", np.min(matrix))
central = matrix[1:3, 1:3]
print("\nCentral 2 x 2 matrix:")
print(central)

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise sums:
[10 26 42 58]

Column-wise sums:
[28 32 36 40]

Mean: 8.5
Maximum: 16
Minimum: 1

Central 2 x 2 matrix:
[[ 6  7]
 [10 11]]


In [52]:
import numpy as np
data = np.random.randn(20)
print("Original data:")
print(data)
print("\nMean:", np.mean(data))
print("Standard deviation:", np.std(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
sorted_data = np.sort(data)
print("\nSorted values:")
print(sorted_data)
new_data = np.where(data < 0, 0, data)
print("\nAfter replacing negative values with 0:")
print(new_data)

Original data:
[-0.32746067 -1.49241771  0.48668003 -0.2763148  -1.58159812 -1.0931951
  0.47074264 -0.52138507 -0.16866354 -0.7758255  -1.2636146  -0.128817
 -0.5034923  -0.29787085  0.27630446 -1.38531214 -0.17848449 -0.64700911
 -0.4374754   0.11871067]

Mean: -0.48632492785446385
Standard deviation: 0.6060019386035649
Minimum: -1.5815981161452606
Maximum: 0.48668003087727263

Sorted values:
[-1.58159812 -1.49241771 -1.38531214 -1.2636146  -1.0931951  -0.7758255
 -0.64700911 -0.52138507 -0.5034923  -0.4374754  -0.32746067 -0.29787085
 -0.2763148  -0.17848449 -0.16866354 -0.128817    0.11871067  0.27630446
  0.47074264  0.48668003]

After replacing negative values with 0:
[0.         0.         0.48668003 0.         0.         0.
 0.47074264 0.         0.         0.         0.         0.
 0.         0.         0.27630446 0.         0.         0.
 0.         0.11871067]


In [53]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

addition = A + B

print("\nElement-wise addition:")
print(addition)

multiplication = A * B

print("\nElement-wise multiplication:")
print(multiplication)
matrix_multiplication = A @ B

print("\nMatrix multiplication:")
print(matrix_multiplication)
transpose = A.T

print("\nTranspose of A:")
print(transpose)
maximum = np.max(matrix_multiplication)
minimum = np.min(matrix_multiplication)

print("\nMaximum of resulting matrix:", maximum)
print("Minimum of resulting matrix:", minimum)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Maximum of resulting matrix: 138
Minimum of resulting matrix: 18


In [54]:
import numpy as np

arr = np.arange(1, 25)

matrix = arr.reshape(4, 6)

print("4 x 6 Matrix:")
print(matrix)

print("\nFirst row:")
print(matrix[0])

print("\nLast row:")
print(matrix[-1])

print("\nFirst two rows:")
print(matrix[:2])


print("\nFirst column:")
print(matrix[:, 0])

print("\nLast column:")
print(matrix[:, -1])

print("\nFirst two columns:")
print(matrix[:, :2])

transpose = matrix.T

print("\nTranspose:")
print(transpose)

print("\nRow sums:")
print(np.sum(matrix, axis=1))

print("\nRow means:")
print(np.mean(matrix, axis=1))

print("\nRow maximum:")
print(np.max(matrix, axis=1))

print("\nRow minimum:")
print(np.min(matrix, axis=1))

print("\nColumn sums:")
print(np.sum(matrix, axis=0))

print("\nColumn means:")
print(np.mean(matrix, axis=0))

print("\nColumn maximum:")
print(np.max(matrix, axis=0))

print("\nColumn minimum:")
print(np.min(matrix, axis=0))

unique_values = np.unique(matrix)

print("\nUnique values:")
print(unique_values)

4 x 6 Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

First row:
[1 2 3 4 5 6]

Last row:
[19 20 21 22 23 24]

First two rows:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

First column:
[ 1  7 13 19]

Last column:
[ 6 12 18 24]

First two columns:
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]]

Transpose:
[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]

Row sums:
[ 21  57  93 129]

Row means:
[ 3.5  9.5 15.5 21.5]

Row maximum:
[ 6 12 18 24]

Row minimum:
[ 1  7 13 19]

Column sums:
[40 44 48 52 56 60]

Column means:
[10. 11. 12. 13. 14. 15.]

Column maximum:
[19 20 21 22 23 24]

Column minimum:
[1 2 3 4 5 6]

Unique values:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
